DESC_COLOUR = 'Modifies a vanity role\'s colour.'
DESC_ICON = 'Modifies a vanity role\'s role icon.'
DESC_ADDROLE = 'Marks a role as vanity and sets its owner.'
DESC_DELROLE = 'Removes a role from this bot\'s database.'
DESC_ROLEPERMS = 'Configure what about a role can be changed.'
DESC_ADDOWNER = 'Add an owner to a vanity role.'
DESC_DELOWNER = 'Remove an owner from a vanity role.'
